### ISSUE TITLE
not able to upload a 1.38 MB photo to the user

### ISSUE THREAD

**Issue by arpit1912** [shobhi1310/backend-team#59]

**Comment by arpit1912** [comment]
check the max size that we can upload moreover it should not allow to select such files(which can't be uploaded)

**Comment by shobhi1310** [comment]
there should either be a compressor as a middleware or a cap from server side, we will have to think on it

**Comment by NobleMathews** [comment]
Multer already has those checks though .. And the selection is actually client side i had made the change in the ejs to allow only images, that could be further restricted to the types currently supported : .png .jpg .gif  & .jpeg
The current upload limit is 50mb, but over 1mb multer sometimes hangs that could be checked i guess or move the load elsewhere.

**Comment by NobleMathews** [comment]
Changed now should work
