### ISSUE TITLE
club_head should not be able to edit or delete any event beyond its occurring date.

### ISSUE THREAD

**Issue by shobhi1310** [shobhi1310/backend-team#86]
> Manage edit delete permissions beyond event occurrence

- Currently all the events can be edited even if the day it was held has been surpassed
- club_head should **neither be allowed to edit** those events.
- **nor delete** them.
- notify should not be allowed
- updating the details should also not be allowed

@NobleMathews  handle this feature.

**Comment by NobleMathews** [comment]
Addressed please review the latest pull.

**Comment by shobhi1310** [comment]
#87
